# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
os:
  - linux
  
# git configs
git:
  depth: 1

# Define the php versions against we want to test our code
php:
    - 5.6
    - 7.0
    - 7.1


matrix:
  fast_finish: true


# We don't want to run linux commands as super user
sudo: false

# Note: Code coverage requires php Xdebug extension  to enabled

# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --no-interaction

# Create a storage folder for Coverage report
before_script:
    - ls -al

# Testing the app (see phpunit.xml), generating Code Coverage report
script:
  - ./vendor/bin/phpunit


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# Configure email notifications
notifications:
     email:
        on_success: never
        on_failure: always

# You can delete cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer

